Python 3.14.6 (tags/v3.14.6:c63aec6, Jun 10 2026, 10:26:10) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
import keyword
help('keuword')
No Python documentation found for 'keuword'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.

help('keyword')
Help on module keyword:

NAME
    keyword - Keywords (from "Grammar/python.gram")

MODULE REFERENCE
    https://docs.python.org/3.14/library/keyword#module-keyword

    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This file is automatically generated; please don't muck it up!

    To update the symbols in this file, 'cd' to the top directory of
    the python source tree and run:

        PYTHONPATH=Tools/peg_generator python3 -m pegen.keywordgen         Grammar/python.gram         Grammar/Tokens         Lib/keyword.py

    Alternatively, you can run 'make regen-keyword'.

FUNCTIONS
    iskeyword = __contains__(object, /) method of builtins.frozenset instance
        x.__contains__(y) <==> y in x.

    issoftkeyword = __contains__(object, /) method of builtins.frozenset instance
        x.__contains__(y) <==> y in x.

DATA
    __all__ = ['iskeyword', 'issoftkeyword', 'kwlist', 'softkwlist']
    kwlist = ['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'aw...
    softkwlist = ['_', 'case', 'match', 'type']

FILE
    c:\users\apeksha\appdata\local\programs\python\python314\lib\keyword.py


>>> help('keywords')
...               

Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 

>>> #to get all 35 keywords in group format._
>>> import keyword
>>> keyword.kwlist
['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
>>> #we can not assign any value to keywords.
>>> #not=100
>>> #how to cjeck whether the keyword is  vaild or not.here we need to follow the syntax.
>>> #import keyword
>>> #keyword.iskeyword("keyword")
>>> #note-->if the given keyword is valid-->output should be true
>>> #         if the given keyword is invalid --.output is false
>>> import keyword
>>> keyword.iskeyword('python')
False
>>> 
>>> import keyword
>>> keyword.iskeyword('is')
True
>>> 
>>> import keyword
... keyword.iskeyword('if')
SyntaxError: multiple statements found while compiling a single statement
